name: CI-Release

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches:
      - main

jobs:
  build-binary:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build binary
        run: |
          docker build . -t builder
          docker run --rm -v ${PWD}:/project builder make
      - uses: actions/upload-artifact@master
        with:
          name: binary
          path: "*.rpx"
